services:

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter-uva
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    command: start-notebook.sh --NotebookApp.token=''

  thingsboard:
    image: thingsboard/tb-postgres
    container_name: thingsboard
    restart: always
    ports:
      - "8090:9090"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ./thingsboard/data:/data
      - ./thingsboard/logs:/var/log/thingsboard

  fastapi:
    build: ./fastapi
    container_name: fastapi-clima
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.7.1
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlflow:/mlflow
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0

  # =========================
  #  POSTGRESQL
  # =========================
  postgres:
    image: postgres:15
    container_name: postgres-avd
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clima
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # =========================
  #  ADMINER (GUI WEB)
  # =========================
  adminer:
    image: adminer
    container_name: adminer-avd
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - postgres

# ================
#  VOLUMES
# ================
volumes:
  pgdata:
    driver: local
